SELECT 
    BK.CATEGORY
    ,SUM(BS.SALES) AS TOTAL_SALES
FROM BOOK_SALES BS
JOIN BOOK BK ON BS.BOOK_ID = BK.BOOK_ID
WHERE DATE_FORMAT(BS.SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY BK.CATEGORY
ORDER BY CATEGORY