SELECT 
    BK.AUTHOR_ID
    ,AR.AUTHOR_NAME
    ,BK.CATEGORY
    ,SUM(BK.PRICE * BS.SALES) AS TOTAL_SALES
FROM BOOK BK
JOIN AUTHOR AR ON BK.AUTHOR_ID = AR.AUTHOR_ID
JOIN BOOK_SALES BS ON BK.BOOK_ID = BS.BOOK_ID
WHERE BS.SALES_DATE LIKE '%2022-01%'
GROUP BY BK.AUTHOR_ID, AR.AUTHOR_NAME, BK.CATEGORY
ORDER BY BK.AUTHOR_ID, BK.CATEGORY DESC;